spring.application.name=empleados-grpc

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Empleados}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:agustin}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.web-application-type=none

grpc.server.port=${GRPC_SERVER_PORT:9090}