spring.application.name=empleados-graphql

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/Empleados
spring.datasource.username=devuser
spring.datasource.password=agustin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.graphql.graphiql.enabled=true
